---
kind: pipeline
type: digitalocean
name: default

token:
  from_secret: digital-ocean-token

server:
  image: docker-18-04
  size: s-1vcpu-1gb
  region: nyc1

steps:
- name: greeting
  commands:
  - echo "hello world"
